apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: test
initializers:
  - name: test.initializer.karmalabs.local
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        resources:
          - deploymentconfigs
